import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster as SonnerToaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Webstore - Next.js',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<SonnerToaster
					richColors
					position='bottom-right'
					closeButton
					toastOptions={{
						className: inter.className,
					}}
				/>
				{children}
			</body>
		</html>
	);
}
